### ISSUE TITLE
About repro

### ISSUE THREAD

**Issue by TJU-YDragonW** [Sarinda251/CDFSL-V#1]
Hello, thank you for your work. I saw "from transformers import VideoMAEForVideoClassification, VideoMAEConfig, VideoMAEImageProcessor" in "testFS.py", but did not find CLASS "transformers". Could you upload the relevant code? Thank you very much!

**Comment by Sarinda251** [comment]
This is part of the HuggingFace transformers package that can be installed with pip or conda.
